#!/usr/bin/env bash

set -eu

ENV_FILE=.env
if [[ ! -e $ENV_FILE ]]; then
  echo "$0: no $ENV_FILE file, run 'cp .env.template .env' and fill it in"
  exit 1
fi
# load environment variables from $ENV_FILE 
export $(xargs < "$ENV_FILE")

.venv/bin/python app.py

