"""
This type stub file was generated by pyright.
"""

from ._triopg import connect, create_pool, TrioConnectionProxy as Connection
from .exceptions import *

"""
This type stub file was generated by pyright.
"""
